- hosts: localhost
  connection: local
  gather_facts: false
  tasks: 
    - name: Get facts for all subscriptions, including ones that are disabled.
      azure.azcollection.azure_rm_subscription_info:
  #      client_id: "{{ client_id }}"
  #      secret: "{{ secret }}"
  #      tenant: "{{ tenant }}"
  #      subscription_id: "{{ subscription_id }}"
         all: true
      delegate_to: localhost
      register: todas_suscripciones

      # [ sub1, sub2, sub3 ... sub10 ]




   # - name: Lista todas las VMS para {{ suscripcion }} 
    #  azure.azcollection.azure_rm_vm_info:
    #    client_id: "{{ client_id }}"
    #    secret: "{{ secret }}"
    #    tenant: "{{ tenant }}"
    #    suscripcion: "{{ item.subscription_id }}
    #  loop: "{{ todas_suscripciones.subscription }}"
      


      #  Lista todas las VMS para sub1
      # vmsub1nombre
      # vmsub1 nombre2

      #  Lista todas las VMS para sub2
      
      
